#!/usr/bin/env python3



import pymongo



# MongoDB connection details

mongo_uri = "mongodb://localhost:27017/"



try:

    # Connect to the MongoDB server
    
    client = pymongo.MongoClient(mongo_uri)
    


    # List all database names
    
    database_names = client.list_database_names()
    


    # Print the list of databases
    
    print("List of databases:")
    
    for db_name in database_names:
    
        print(db_name)
	


except pymongo.errors.ConnectionFailure as e:

    print(f"Error: Unable to connect to MongoDB: {e}")
    


finally:

    # Close the MongoDB connection
    
    client.close()
    
