#!/bin/bash


# MongoDB connection details
MONGO_URI="mongodb://localhost:27017"

# Run the MongoDB shell to list databases
mongo $MONGO_URI --eval "printjson(db.adminCommand('listDatabases'))" | grep "name" | cut -d '"' -f 4